
// Categories
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';

// Tabs
const ADD_TAB = 'ADD_TAB';
const GET_CATEGORY_TABS = 'GET_CATEGORY_TABS';
const CHANGE_SELECTED_TAB = 'CHANGE_SELECTED_TAB';